name: Tests
on:
  pull_request:
  push:
defaults:
  run:
    working-directory: ./
jobs:
  run:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php: [8.2]
        laravel: [10]
        phpunit-versions: ["latest"]
    name: PHP:${{ matrix.php }} / Laravel:${{ matrix.laravel }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup PHP, with composer and extensions
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: bcmath, mbstring, intl, amqp, dba, pdo, sqlite, pdo_sqlite
          tools: composer:v2
          coverage: none
          ini-values: error_reporting=E_ALL

      - name: Set Laravel Version
        run: composer require "laravel/framework:^${{ matrix.laravel }}" --no-update

      - name: Get composer cache directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Cache composer dependencies
        uses: actions/cache@v2
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: dependencies-laravel-${{ matrix.laravel }}-php-${{ matrix.php }}-composer-${{ hashFiles('composer.json') }}
          restore-keys: dependencies-laravel-${{ matrix.laravel }}-php-${{ matrix.php }}-composer-

      - name: Install dependencies
        uses: nick-fields/retry@v2
        with:
          timeout_minutes: 5
          max_attempts: 5
          command: composer update --prefer-dist --no-interaction --no-progress

      - name: Execute tests (Unit and Feature tests) via Pest
        env:
          APP_ENV: testing
          DB_DATABASE: ":memory:"
          PAYMENT_DRIVER: mollie
          MOLLIE_API_KEY: test_xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
        run: composer test
